---
author:
  - name: John Doe
    affiliation:
      - name: Dummy org
        department: Cool Dep
        address: Somewhere
        city: Magic city
        country: best one
        postal-code: 9999
address:
  - Director Doe & Co
  - 35 Anthony Road
  - Newport
  - Ipswich IP3 5RT
subject: collaboration
opening: "Dear Sir or Madam,"
closing: "Yours Faithfully,"
format:
  letter-pdf:
    keep-tex: true
---

I am writing to you about a project I am doing. I hope you like this table:

```{r}
#| echo: false
knitr::kable(mtcars[1:2,])
```

The figure is also informative.

```{r}
#| echo: false
#| warning: false
#| fig-height: 2
library(ggplot2)
df <- data.frame(
  gp = factor(rep(letters[1:3], each = 10)),
  y = rnorm(30)
)
ds <- do.call(rbind, lapply(split(df, df$gp), function(d) {
  data.frame(mean = mean(d$y), sd = sd(d$y), gp = d$gp)
}))
ggplot(df, aes(gp, y)) +
  geom_point() +
  geom_point(data = ds, aes(y = mean), colour = 'red', size = 3)
```

Thank you for your time and consideration.

I look forward to your reply.
